# .github/workflows/ci.yml
name: CyberEditor CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- ADD THIS DEBUGGING STEP ---
    - name: List files in the repository
      run: ls -la
    # -----------------------------

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        # IMPORTANT: We can also add an explicit check for the lock file
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Build TypeScript
      run: npm run build
